### PR TITLE
Diagnostic data: include SDK version and git hash

### PR DESCRIPTION
**Pull request by ok300**
This PR adds the SDK version in the diagnostic data output:

```
***Version***
SDK v0.5.2 (23c25faac7)
```

### CODE REVIEW

**Review by erdemyerebasmaz — APPROVED** [review]
LGTM

**Comment by JssDWt** [comment]
@ok300 Is it an idea to rebase this PR on top of 6c30f3f8fe7bf9e1e5953a8526344f7da4bd5b3a?
That commit is uncontroversial I think, so let's at least make things json and figure out the hex encoding later?

**Comment by ok300** [comment]
@JssDWt good idea. I'll wait until you merge the JSON hex PR, then I'll rebase this one.

**Comment by JssDWt** [comment]
> @JssDWt good idea. I'll wait until you merge the JSON hex PR, then I'll rebase this one.

I'm off until Friday, maybe you can include that commit in this PR for now. Just the commit that creates the json document, not the hex serializer.

**Comment by ok300** [comment]
I rebased on #1091 .

**Review by dangeross — APPROVED** [review]

**Pull request merged**
